apiVersion: v1
kind: Namespace
metadata:
  name: team-b
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: team-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      nodeSelector:
        team: team-b
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: '1'
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inflate-pdb
  namespace: team-b
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: inflate
