apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-workflows
  generateName: karpenter-rollback-
  annotations:
    workflows.argoproj.io/description: |
      This workflow rollback from karpenter to nodegroups
spec:
  podMetadata:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  ttlStrategy:
    secondsAfterCompletion: 600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
  automountServiceAccountToken: true
  volumes:
    - name: lib
      configMap:
        name: karpenter-migrator
  serviceAccountName: argo-workflow
  entrypoint: migrate
  templates:
  - name: migrate
    steps:
    - - name: get-nodegroups
        template: get-nodegroups
    - - name: rollback-nodegroup
        template: rollback-nodegroup
        arguments:
          parameters:
          - name: nodegroup_name
            value: "{{item.nodegroup_name}}"
          - name: cluster
            value: "{{item.cluster}}"
        withParam: "{{steps.get-nodegroups.outputs.result}}"


  - name: get-nodegroups
    script:
      volumeMounts:
        - name: lib
          mountPath: "/argo/staging/infralib.py"
          subPath: "infralib.py"
      image: csantanapr/python-argocon:1.1
      command: [python]
      source: |
        import boto3
        import sys
        import json
        from infralib import *

        session = boto3.Session()
        eks = session.client('eks')
        cluster = 'argocon-1'
        nodegroups = get_eks_cluster_nodegroups(eks, cluster)
        # create new array out of nodegroups array with each item on object with keys cluster and nodegroup
        nodegroups = [{'cluster': cluster, 'nodegroup_name': ng} for ng in nodegroups]
        json.dump(nodegroups, sys.stdout)

  - name: rollback-nodegroup
    inputs:
      parameters:
      - name: nodegroup_name
      - name: cluster
    script:
      volumeMounts:
        - name: lib
          mountPath: "/argo/staging/infralib.py"
          subPath: "infralib.py"
      image: csantanapr/python-argocon:1.1
      command: [python]
      source: |
        nodegroup_name = "{{inputs.parameters.nodegroup_name}}"
        cluster = "{{inputs.parameters.cluster}}"
        print("nodegroup_name: " + nodegroup_name)
        print("cluster: " + cluster)

        import boto3
        import sys
        import json
        import yaml
        from infralib import *

        session = boto3.Session()
        eks = session.client('eks')

        # Get the corresponding karpenter node pool
        print("Restoring Node Group "+nodegroup_name +
              " from corresponding NodePool")
        k8s_karpenter_node_pool = get_custom_object(nodegroup_name, "NodePool")
        # if k8s_karpenter_node_pool is None then continue
        if k8s_karpenter_node_pool is None:
            sys.exit(0)
        # Get the scaling config from annotations
        min_size = int(
            k8s_karpenter_node_pool['metadata']['annotations']['migrate.karpenter.io/min'])
        max_size = int(
            k8s_karpenter_node_pool['metadata']['annotations']['migrate.karpenter.io/max'])
        desired_size = int(
            k8s_karpenter_node_pool['metadata']['annotations']['migrate.karpenter.io/desired'])
        # remove NO_EXECUTE taint from nodes and restore scalingConfig
        print("Restoring scaling config for nodegroup "+nodegroup_name)
        update_nodegroup(
            eks,
            clusterName=cluster,
            nodegroupName=nodegroup_name,
            scalingConfig={
                'desiredSize': desired_size,
                'minSize': min_size,
                'maxSize': max_size
            }
        )
        # scale cluster-autoscaler to zero
        scale_deployment(
            "cluster-autoscaler-aws-cluster-autoscaler", "kube-system", 1)

        # Delete nodepool and nodeclass
        print("Deleting NodePool"+nodegroup_name)
        delete_custom_object(nodegroup_name, "NodePool")
        print("Deleting NodeClass for nodegroup "+nodegroup_name)
        delete_custom_object(nodegroup_name, "EC2NodeClass")



