---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: team-a-20240203045439786800000003
spec:
  amiFamily: AL2
  role: arn:aws:iam::015299085168:role/team-a-eks-node-group-20240202055634320200000005
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter
  subnetSelectorTerms:
  - id: subnet-0a9410a96a6f1aa50
  - id: subnet-0fc4a9eeeddaa848e
  - id: subnet-075e9448c75b1e6b2
  tags:
    Blueprint: karpenter
    GithubRepo: github.com/gitops-bridge-dev/kubecon-2023-eu-argocon
    Name: team-a
    karpenter.sh/discovery: karpenter

---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: team-a-20240203045439786800000003
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 1000
  template:
    metadata:
      labels:
        event: argocon-eu-2024
        team: team-a
        type: node-group
    spec:
      nodeClassRef:
        name: team-a-20240203045439786800000003
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - t3.medium

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: team-b-20240203045439786700000001
spec:
  amiFamily: AL2
  role: arn:aws:iam::015299085168:role/team-b-eks-node-group-20240202055634322500000006
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter
  subnetSelectorTerms:
  - id: subnet-0a9410a96a6f1aa50
  - id: subnet-0fc4a9eeeddaa848e
  - id: subnet-075e9448c75b1e6b2
  tags:
    Blueprint: karpenter
    GithubRepo: github.com/gitops-bridge-dev/kubecon-2023-eu-argocon
    Name: team-b
    karpenter.sh/discovery: karpenter

---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: team-b-20240203045439786700000001
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 1000
  template:
    metadata:
      labels:
        event: argocon-eu-2024
        team: team-b
        type: node-group
    spec:
      nodeClassRef:
        name: team-b-20240203045439786700000001
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - m5.large

