apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-workflows
  generateName: karpenter-migrate-
  annotations:
    workflows.argoproj.io/description: |
      This workflow migrate nodegroups to karpenter.
spec:
  entrypoint: migrate
  arguments:
    parameters:
    - name: cluster
      value: argocon-1
  workflowTemplateRef:
    name: karpenter-migrate
