apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-workflows
  generateName: karpenter-rollback-
  annotations:
    workflows.argoproj.io/description: |
      This workflow rollback from karpenter to nodegroups
spec:
  entrypoint: rollback
  arguments:
    parameters:
    - name: cluster
      value: argocon-1
  workflowTemplateRef:
    name: karpenter-rollback
